#!/usr/bin/env node
// bench/blackbox/driver.js — the BLACK-BOX bench driver: a virtual "person" talking to ANY voice
// agent over real audio devices. No integration with the system under test at all — it only needs
// the agent's mic pointed at `bench_mic` and its output at `bench_spk` (see audio-setup.sh).
//
//   person WAVs ──▶ pacat ▶ bench_mic ▶ [ SYSTEM UNDER TEST ] ▶ bench_spk ▶ pacat ▶ Gate + recording
//
// The driver is REACTIVE, like a real person: it waits for the agent to answer (speech onset on the
// speaker side), fires scripted interruptions N ms into the agent's actual audio, and moves to the
// next line once the agent has settled. Everything is recorded — the timeline (same event shape as
// the instrumented harness) plus the full agent audio for offline analysis/transcription.
//
// Usage:
//   bench/blackbox/audio-setup.sh up
//   node bench/blackbox/driver.js [scenario] [label]        # then start the agent, talking begins
//                                                           # at its first mic connection or T+startDelayMs
// Output: bench/results/bb-<scenario>-<label>-<ts>.json (+ .agent.wav) — analyze.js turns it into a report.

import { spawn } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync, existsSync, createWriteStream } from 'node:fs';
import { join, normalize } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Gate, RATE } from './energy.js';

const BENCH = normalize(join(fileURLToPath(import.meta.url), '..', '..'));   // works nested (voiceloop/bench) or standalone
const scenarioName = process.argv[2] || 'smalltalk';
const label = process.argv[3] || 'blackbox';
const scenario = JSON.parse(readFileSync(join(BENCH, 'scenarios', `${scenarioName}.json`), 'utf8'));

const AUDIO_DIR = join(BENCH, 'audio', scenario.audio ?? scenarioName);   // scenario.audio: reuse another scenario's renders (echo = smalltalk lines + coupling)
const CHUNK_MS = 100, CHUNK_BYTES = (RATE * 2 * CHUNK_MS) / 1000;
const SETTLE_MS = scenario.settleMs ?? 2500;   // agent silent this long after speaking = reply over (person's patience at a pause)
const REPLY_TIMEOUT_MS = 20000;  // agent never answered → move on, metrics show the hole
const now = () => performance.now();

// Person utterances: raw s16le mono 16k, pre-generated by gen-audio.js.
const utt = scenario.turns.map((_, k) => {
  const f = join(AUDIO_DIR, `person-${k}.raw`);
  if (!existsSync(f)) { console.error(`missing ${f} — run: node bench/blackbox/gen-audio.js ${scenarioName}`); process.exit(1); }
  return readFileSync(f);
});

// ── echo coupling (scenario.echo: { gainDb, delayMs }) ─────────────────────────────────────────
// Simulates a laptop speaker→mic acoustic path: the agent's own output, attenuated and delayed,
// mixed back into the mic. SOFTWARE mix in the driver (not a pulse loopback module): the driver
// already taps bench_spk.monitor, so scaling those samples into the outgoing mic chunks is fully
// deterministic — same gain every run, no module lifetime/permission state on the machine.
// Timing: echoBuf is pre-charged with delayMs of silence; producer (pacat record) and consumer
// (the 100ms mic tick) both run realtime, so the nominal delay only gains pacat latency (~40ms
// per side) + tick quantization — an effective ~70–200ms acoustic path, the realistic range for
// speaker→mic on consumer devices. Samples clamp at int16 (loud overlap clips, like a real mic).
const echo = scenario.echo;
const echoGain = echo ? Math.pow(10, (echo.gainDb ?? -15) / 20) : 0;
let echoBuf = echo ? Buffer.alloc(Math.round((RATE * 2 * (echo.delayMs ?? 30)) / 1000) & ~1) : null;

// ── background noise (scenario.noise: { bed } + per-turn noiseBurst) ───────────────────────────
// The bed (café chatter + floor, pre-scaled to ~15dB SNR by gen-noise.js) loops into the mic
// CONTINUOUSLY — through person lines, agent replies and the gaps; a quiet moment for an energy
// VAD never comes. Bursts (cough/door, person-line loudness) are queued mid-reply by fireBurst().
// Mixing is a saturating per-sample add, same as the echo path above.
const bed = scenario.noise?.bed ? readFileSync(join(AUDIO_DIR, scenario.noise.bed)) : null;
const burstPcm = Object.fromEntries(scenario.turns.filter((t) => t.noiseBurst)
  .map((t) => [t.noiseBurst.file, readFileSync(join(AUDIO_DIR, t.noiseBurst.file))]));
let bedOff = 0, burst = null, burstOff = 0, burstMeta = null;

// ── mic side: one continuous realtime stream (agents need an always-live mic) ──────────────────
const mic = spawn('pacat', ['--playback', '-d', 'bench_mic_sink', '--raw', `--rate=${RATE}`, '--channels=1', '--format=s16le', '--latency-msec=40']);
mic.on('exit', (c) => { if (c) { console.error('pacat mic exited', c); process.exit(1); } });
let micQueue = Buffer.alloc(0);                     // utterance bytes waiting to be streamed
const silence = Buffer.alloc(CHUNK_BYTES);
setInterval(() => {                                  // realtime pacing: one 100ms chunk per tick
  const chunk = micQueue.length ? micQueue.subarray(0, CHUNK_BYTES) : silence;
  if (micQueue.length) micQueue = micQueue.subarray(chunk.length);
  let out = chunk.length === CHUNK_BYTES ? chunk : Buffer.concat([chunk, silence.subarray(chunk.length)]);
  if (echoBuf?.length >= 2) {                        // mix the delayed agent echo into this chunk
    const take = echoBuf.subarray(0, Math.min(CHUNK_BYTES, echoBuf.length & ~1));
    echoBuf = echoBuf.subarray(take.length);
    out = Buffer.from(out);                          // never mutate micQueue/silence views
    for (let i = 0; i + 1 < take.length; i += 2) {
      const v = out.readInt16LE(i) + take.readInt16LE(i);
      out.writeInt16LE(v > 32767 ? 32767 : v < -32768 ? -32768 : v, i);
    }
  }
  if (bed || burst) {                                // mix noise bed (looped) + any active burst
    // noise_burst is emitted HERE, on the tick that injects the first burst sample — not when
    // fireBurst() queued it — so the event is ground truth for when noise actually hit the mic.
    if (burst && burstOff === 0) { ev('noise_burst', burstMeta); console.log(`burst '${burstMeta.kind}' → mic`); }
    out = out === chunk || out === silence ? Buffer.from(out) : out;
    for (let i = 0; i + 1 < out.length; i += 2) {
      let v = out.readInt16LE(i);
      if (bed) { v += bed.readInt16LE(bedOff); bedOff = (bedOff + 2) % bed.length; }
      if (burst) { v += burst.readInt16LE(burstOff); if ((burstOff += 2) >= burst.length) { burst = null; burstOff = 0; } }
      out.writeInt16LE(v > 32767 ? 32767 : v < -32768 ? -32768 : v, i);
    }
  }
  mic.stdin.write(out);
}, CHUNK_MS);

// ── speaker side: record + live speech gate ────────────────────────────────────────────────────
const events = [];
const ev = (type, extra = {}) => events.push({ t: Math.round(now() - t0), epoch: Date.now(), type, ...extra });
const spk = spawn('pacat', ['--record', '-d', 'bench_spk.monitor', '--raw', `--rate=${RATE}`, '--channels=1', '--format=s16le', '--latency-msec=40']);
spk.on('exit', (c) => { if (c && !done) { console.error('pacat spk exited', c); process.exit(1); } });

const dir = join(BENCH, 'results');
if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
const stamp = new Date().toISOString().replace(/[:.]/g, '-');
const base = join(dir, `bb-${scenarioName}-${label}-${stamp}`);
const rec = createWriteStream(`${base}.agent.raw`);

let t0 = now(), recAnchor = null, agentSpeaking = false, lastAgentEdge = 0, done = false;
const gate = new Gate({
  onSpeech: (tMs) => { agentSpeaking = true; lastAgentEdge = recAnchor + tMs; ev('clip_start', { t: Math.round(recAnchor + tMs - t0) }); },
  onSilence: (tMs) => { agentSpeaking = false; lastAgentEdge = recAnchor + tMs; ev('clip_end', { t: Math.round(recAnchor + tMs - t0) }); },
});
spk.stdout.on('data', (c) => {
  recAnchor ??= now(); rec.write(c); gate.feed(c);
  if (echo) {                                        // speaker → mic coupling: append attenuated copy
    const scaled = Buffer.alloc(c.length & ~1);
    for (let i = 0; i + 1 < scaled.length; i += 2) scaled.writeInt16LE(Math.round(c.readInt16LE(i) * echoGain), i);
    echoBuf = Buffer.concat([echoBuf, scaled]);
  }
});

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const waitFor = async (cond, timeout) => { const end = now() + timeout; while (!cond() && now() < end) await sleep(20); return cond(); };

// Queue this turn's noiseBurst afterMs into THIS turn's reply. Fresh-onset semantics: right after
// person_end the PREVIOUS reply may still be draining (barge-in turns), so first wait for silence,
// then for the new reply's audio. The mic tick emits the noise_burst event when it injects the
// first sample (ground truth for analyze.js attribution).
async function fireBurst(k, nb) {
  await waitFor(() => !agentSpeaking, REPLY_TIMEOUT_MS);
  if (!(await waitFor(() => agentSpeaking, REPLY_TIMEOUT_MS))) return console.log(`turn ${k}: no reply — burst '${nb.kind}' skipped`);
  await sleep(nb.afterMs);
  const pcm = burstPcm[nb.file];
  burstMeta = { turn: k, kind: nb.kind, durMs: Math.round((pcm.length / 2 / RATE) * 1000) };
  burst = pcm; burstOff = 0;
  console.log(`turn ${k}: burst '${nb.kind}' queued @${nb.afterMs}ms into reply`);
}

// ── the conversation ───────────────────────────────────────────────────────────────────────────
(async () => {
  console.log(`driver: scenario=${scenario.name} turns=${scenario.turns.length}${echo ? ` echo=${echo.gainDb ?? -15}dB/${echo.delayMs ?? 30}ms` : ''}${bed ? ` noise-bed=${(bed.length / 2 / RATE).toFixed(1)}s loop` : ''} → speak into bench_mic, listen on bench_spk`);
  console.log('driver: start your agent now — first line plays in', (scenario.startDelayMs ?? 5000) / 1000, 's');
  await sleep(scenario.startDelayMs ?? 5000);
  t0 = now();

  for (let k = 0; k < scenario.turns.length; k++) {
    const turn = scenario.turns[k];
    if (turn.interrupt) {
      // Fire afterMs into the agent's CURRENT reply — wait for its audio if it hasn't started yet.
      await waitFor(() => agentSpeaking, REPLY_TIMEOUT_MS);
      await sleep(turn.interrupt.afterMs);
    } else if (k > 0) {
      // Natural turn-taking: wait until the agent answered and has settled (or timed out silent).
      const spoke = await waitFor(() => agentSpeaking, REPLY_TIMEOUT_MS);
      if (spoke) await waitFor(() => !agentSpeaking && now() - lastAgentEdge > SETTLE_MS, REPLY_TIMEOUT_MS);
      await sleep(300);   // beat before speaking again, like a person
    }
    ev('person_start', { turn: k });
    micQueue = Buffer.concat([micQueue, utt[k]]);
    const durMs = (utt[k].length / 2 / RATE) * 1000;
    await sleep(durMs);
    ev('person_end', { turn: k });
    console.log(`turn ${k}: "${turn.person}" (${Math.round(durMs)}ms${turn.interrupt ? `, interrupt @${turn.interrupt.afterMs}ms` : ''})`);
    if (turn.noiseBurst) fireBurst(k, turn.noiseBurst);   // fire-and-forget; the next turn's settle wait outlives it
  }

  // Let the final reply play out fully, then close.
  await waitFor(() => agentSpeaking, REPLY_TIMEOUT_MS);
  await waitFor(() => !agentSpeaking && now() - lastAgentEdge > SETTLE_MS, 60000);
  done = true;
  rec.end(); mic.stdin.end(); spk.kill(); mic.kill();
  // audioStartMs: where driver t=0 falls on the RECORDING's clock (recording starts at stream open,
  // before the countdown) — analyze.js needs it to re-base offline audio segments into driver time.
  writeFileSync(`${base}.json`, JSON.stringify({ scenario: scenarioName, label, mode: 'blackbox', audioStartMs: Math.round(t0 - recAnchor), events }, null, 2));
  console.log(`\nrecorded ${events.length} events → ${base}.json\nanalyze: node bench/blackbox/analyze.js ${base}.json`);
  process.exit(0);
})();
