#!/usr/bin/env node
// bench/blackbox/driver.js — the BLACK-BOX bench driver: a virtual "person" talking to ANY voice
// agent over real audio devices. No integration with the system under test at all — it only needs
// the agent's mic pointed at `bench_mic` and its output at `bench_spk` (see audio-setup.sh).
//
//   person WAVs ──▶ pacat ▶ bench_mic ▶ [ SYSTEM UNDER TEST ] ▶ bench_spk ▶ pacat ▶ Gate + recording
//
// The driver is REACTIVE, like a real person: it waits for the agent to answer (speech onset on the
// speaker side), fires scripted interruptions N ms into the agent's actual audio, and moves to the
// next line once the agent has settled. Everything is recorded — the timeline (same event shape as
// the instrumented harness) plus the full agent audio for offline analysis/transcription.
//
// Usage:
//   bench/blackbox/audio-setup.sh up
//   node bench/blackbox/driver.js [scenario] [label]        # then start the agent, talking begins
//                                                           # at its first mic connection or T+startDelayMs
// Output: bench/results/bb-<scenario>-<label>-<ts>.json (+ .agent.wav) — analyze.js turns it into a report.

import { spawn } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync, existsSync, createWriteStream } from 'node:fs';
import { join, normalize } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Gate, RATE } from './energy.js';

const ROOT = normalize(join(fileURLToPath(import.meta.url), '..', '..', '..'));
const scenarioName = process.argv[2] || 'smalltalk';
const label = process.argv[3] || 'blackbox';
const scenario = JSON.parse(readFileSync(join(ROOT, 'bench', 'scenarios', `${scenarioName}.json`), 'utf8'));

const AUDIO_DIR = join(ROOT, 'bench', 'audio', scenarioName);
const CHUNK_MS = 100, CHUNK_BYTES = (RATE * 2 * CHUNK_MS) / 1000;
const SETTLE_MS = scenario.settleMs ?? 2500;   // agent silent this long after speaking = reply over (person's patience at a pause)
const REPLY_TIMEOUT_MS = 20000;  // agent never answered → move on, metrics show the hole
const now = () => performance.now();

// Person utterances: raw s16le mono 16k, pre-generated by gen-audio.js.
const utt = scenario.turns.map((_, k) => {
  const f = join(AUDIO_DIR, `person-${k}.raw`);
  if (!existsSync(f)) { console.error(`missing ${f} — run: node bench/blackbox/gen-audio.js ${scenarioName}`); process.exit(1); }
  return readFileSync(f);
});

// ── mic side: one continuous realtime stream (agents need an always-live mic) ──────────────────
const mic = spawn('pacat', ['--playback', '-d', 'bench_mic_sink', '--raw', `--rate=${RATE}`, '--channels=1', '--format=s16le', '--latency-msec=40']);
mic.on('exit', (c) => { if (c) { console.error('pacat mic exited', c); process.exit(1); } });
let micQueue = Buffer.alloc(0);                     // utterance bytes waiting to be streamed
const silence = Buffer.alloc(CHUNK_BYTES);
setInterval(() => {                                  // realtime pacing: one 100ms chunk per tick
  const chunk = micQueue.length ? micQueue.subarray(0, CHUNK_BYTES) : silence;
  if (micQueue.length) micQueue = micQueue.subarray(chunk.length);
  mic.stdin.write(chunk.length === CHUNK_BYTES ? chunk : Buffer.concat([chunk, silence.subarray(chunk.length)]));
}, CHUNK_MS);

// ── speaker side: record + live speech gate ────────────────────────────────────────────────────
const events = [];
const ev = (type, extra = {}) => events.push({ t: Math.round(now() - t0), epoch: Date.now(), type, ...extra });
const spk = spawn('pacat', ['--record', '-d', 'bench_spk.monitor', '--raw', `--rate=${RATE}`, '--channels=1', '--format=s16le', '--latency-msec=40']);
spk.on('exit', (c) => { if (c && !done) { console.error('pacat spk exited', c); process.exit(1); } });

const dir = join(ROOT, 'bench', 'results');
if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
const stamp = new Date().toISOString().replace(/[:.]/g, '-');
const base = join(dir, `bb-${scenarioName}-${label}-${stamp}`);
const rec = createWriteStream(`${base}.agent.raw`);

let t0 = now(), recAnchor = null, agentSpeaking = false, lastAgentEdge = 0, done = false;
const gate = new Gate({
  onSpeech: (tMs) => { agentSpeaking = true; lastAgentEdge = recAnchor + tMs; ev('clip_start', { t: Math.round(recAnchor + tMs - t0) }); },
  onSilence: (tMs) => { agentSpeaking = false; lastAgentEdge = recAnchor + tMs; ev('clip_end', { t: Math.round(recAnchor + tMs - t0) }); },
});
spk.stdout.on('data', (c) => { recAnchor ??= now(); rec.write(c); gate.feed(c); });

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const waitFor = async (cond, timeout) => { const end = now() + timeout; while (!cond() && now() < end) await sleep(20); return cond(); };

// ── the conversation ───────────────────────────────────────────────────────────────────────────
(async () => {
  console.log(`driver: scenario=${scenario.name} turns=${scenario.turns.length} → speak into bench_mic, listen on bench_spk`);
  console.log('driver: start your agent now — first line plays in', (scenario.startDelayMs ?? 5000) / 1000, 's');
  await sleep(scenario.startDelayMs ?? 5000);
  t0 = now();

  for (let k = 0; k < scenario.turns.length; k++) {
    const turn = scenario.turns[k];
    if (turn.interrupt) {
      // Fire afterMs into the agent's CURRENT reply — wait for its audio if it hasn't started yet.
      await waitFor(() => agentSpeaking, REPLY_TIMEOUT_MS);
      await sleep(turn.interrupt.afterMs);
    } else if (k > 0) {
      // Natural turn-taking: wait until the agent answered and has settled (or timed out silent).
      const spoke = await waitFor(() => agentSpeaking, REPLY_TIMEOUT_MS);
      if (spoke) await waitFor(() => !agentSpeaking && now() - lastAgentEdge > SETTLE_MS, REPLY_TIMEOUT_MS);
      await sleep(300);   // beat before speaking again, like a person
    }
    ev('person_start', { turn: k });
    micQueue = Buffer.concat([micQueue, utt[k]]);
    const durMs = (utt[k].length / 2 / RATE) * 1000;
    await sleep(durMs);
    ev('person_end', { turn: k });
    console.log(`turn ${k}: "${turn.person}" (${Math.round(durMs)}ms${turn.interrupt ? `, interrupt @${turn.interrupt.afterMs}ms` : ''})`);
  }

  // Let the final reply play out fully, then close.
  await waitFor(() => agentSpeaking, REPLY_TIMEOUT_MS);
  await waitFor(() => !agentSpeaking && now() - lastAgentEdge > SETTLE_MS, 60000);
  done = true;
  rec.end(); mic.stdin.end(); spk.kill(); mic.kill();
  // audioStartMs: where driver t=0 falls on the RECORDING's clock (recording starts at stream open,
  // before the countdown) — analyze.js needs it to re-base offline audio segments into driver time.
  writeFileSync(`${base}.json`, JSON.stringify({ scenario: scenarioName, label, mode: 'blackbox', audioStartMs: Math.round(t0 - recAnchor), events }, null, 2));
  console.log(`\nrecorded ${events.length} events → ${base}.json\nanalyze: node bench/blackbox/analyze.js ${base}.json`);
  process.exit(0);
})();
